# Generated by Django 3.1.4 on 2021-07-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210716_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='user_name',
        ),
    ]
