# Generated by Django 3.1.4 on 2021-07-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210716_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
