version: '3.8'
services:
    app:
        build: .
        volumes: 
            - .:/django
        ports:
            - 8000:8000
        image: app:django
        container_name: akantbook_container
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1