# Generated by Django 3.1.4 on 2021-07-16 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('Type_of_service', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], max_length=50)),
                ('business_email_address', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business_Account',
                'verbose_name_plural': 'Business_Accounts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Description', models.TextField(max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business_account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('image', models.ImageField(upload_to=None)),
                ('current_product_stock_available', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business_account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('quanties_of_product_sold', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('POS', 'POS'), ('TRANSFER', 'TRANSFER'), ('CREDIT', 'CREDIT')], max_length=50)),
                ('reference_note', models.TextField(max_length=250)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business_account')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('productSold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('Profit', 'Profit'), ('Rentals', 'Rentals'), ('Sales', 'Sales'), ('Dividend', 'Dividend'), ('Loan', 'Loan'), ('Investments', 'Investments'), ('Donations', 'Donations')], max_length=50)),
                ('amount', models.FloatField()),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business_account')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Tax', 'Tax'), ('Electricity', 'Electricity'), ('Transportation', 'Transportation'), ('Rent', 'Rent'), ('Raw Materials', 'Raw Materials'), ('Salary', 'Salary'), ('Loan', 'Loan'), ('Insurance', 'Insurance'), ('Utilities', 'Utilities'), ('Savings', 'Savings'), ('Maintenance & Repairs', 'Maintenance & Repairs'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('amount', models.FloatField()),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(max_length=500)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('POS', 'POS'), ('TRANSFER', 'TRANSFER'), ('CREDIT', 'CREDIT')], max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business_account')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
