# Generated by Django 3.1.3 on 2020-12-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('Type_of_service', models.CharField(choices=[('G', 'Goods'), ('S', 'Services')], max_length=1)),
                ('business_email_address', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Business_Account',
                'verbose_name_plural': 'Business_Accounts',
            },
        ),
    ]
