# Generated by Django 3.1.3 on 2020-12-15 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_note', models.TextField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('Profit', 'Profit'), ('Rentals', 'Rentals'), ('Sales', 'Sales'), ('Dividend', 'Dividend'), ('Investments', 'Investments'), ('Donations', 'Donations')], max_length=50)),
                ('amount', models.FloatField()),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Tax', 'Tax'), ('Electricity', 'Electricity'), ('Transportation', 'Transportation'), ('Rent', 'Rent'), ('Raw Materials', 'Raw Materials'), ('Salary', 'Salary'), ('Loan', 'Loan'), ('Insurance', 'Insurance'), ('Maintenance & Repairs', 'Maintenance & Repairs'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('amount', models.FloatField()),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Business_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('Type_of_service', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], max_length=50)),
                ('business_email_address', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business_Account',
                'verbose_name_plural': 'Business_Accounts',
            },
        ),
    ]
