# Generated by Django 3.1.4 on 2021-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_note',
            field=models.CharField(default='fe38d37e-e80e-11eb-b261-b4b52f8277a3', max_length=50),
        ),
    ]
