# Generated by Django 3.1.3 on 2020-12-14 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_business_account_adminstrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('T', 'Tax'), ('E', 'Electricity'), ('TS', 'Transportation'), ('R', 'Rent'), ('RM', 'Raw Materials'), ('S', 'Salary'), ('L', 'Loan'), ('I', 'Insurance'), ('M/R', 'Maintenance & Repairs'), ('MS', 'Miscellaneous')], max_length=3)),
                ('amount', models.FloatField()),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Profit'), ('R', 'Rentals'), ('S', 'Sales'), ('D', 'Dividend'), ('I', 'Investments'), ('DO', 'Donations')], max_length=250)),
                ('amount', models.FloatField()),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.AlterField(
            model_name='business_account',
            name='adminstrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_note', models.TextField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
