# Generated by Django 3.1.4 on 2021-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210718_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference_note',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_num',
            field=models.CharField(default='061ff97a-e80f-11eb-a924-b4b52f8277a3', max_length=50),
        ),
    ]
