# Generated by Django 3.1.3 on 2020-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201214_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_account',
            name='Type_of_service',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Type',
            field=models.CharField(choices=[('Tax', 'Tax'), ('Electricity', 'Electricity'), ('Transportation', 'Transportation'), ('Rent', 'Rent'), ('Raw Materials', 'Raw Materials'), ('Salary', 'Salary'), ('Loan', 'Loan'), ('Insurance', 'Insurance'), ('Maintenance & Repairs', 'Maintenance & Repairs'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(choices=[('Profit', 'Profit'), ('Rentals', 'Rentals'), ('Sales', 'Sales'), ('Dividend', 'Dividend'), ('Investments', 'Investments'), ('Donations', 'Donations')], max_length=50),
        ),
    ]
