# Generated by Django 3.1.4 on 2021-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210718_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_num',
            field=models.CharField(default='08d79134-e80f-11eb-bee4-b4b52f8277a3', max_length=50),
        ),
    ]
