# Generated by Django 3.1.4 on 2021-06-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210623_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='user',
            new_name='business',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.business_account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.business_account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.business_account'),
            preserve_default=False,
        ),
    ]
