# Generated by Django 3.1.3 on 2020-12-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201215_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='income_type',
        ),
    ]
