# Generated by Django 3.1.4 on 2021-06-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210624_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='business',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
