# Generated by Django 3.1.4 on 2021-07-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210718_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='customerName',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_num',
            field=models.CharField(default='42c5f16c-e818-11eb-a236-b4b52f8277a3', editable=False, max_length=50),
        ),
    ]
