# Generated by Django 3.1.4 on 2021-07-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210718_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_num',
            field=models.CharField(default='5e8da05c-e818-11eb-a7b6-b4b52f8277a3', editable=False, max_length=50),
        ),
    ]
