# Generated by Django 3.1.4 on 2021-06-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210624_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('image', models.ImageField(upload_to=None)),
                ('quantities_currently_available', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business_account')),
            ],
        ),
    ]
