# Generated by Django 3.1.4 on 2021-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210624_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quanties_of_product_sold',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
