# Generated by Django 3.1.4 on 2021-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantities_currently_available',
            new_name='current_product_stock_available',
        ),
        migrations.AddField(
            model_name='expenses',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('POS', 'POS'), ('TRANSFER', 'TRANSFER'), ('CREDIT', 'CREDIT')], default='pos', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Type',
            field=models.CharField(choices=[('Tax', 'Tax'), ('Electricity', 'Electricity'), ('Transportation', 'Transportation'), ('Rent', 'Rent'), ('Raw Materials', 'Raw Materials'), ('Salary', 'Salary'), ('Loan', 'Loan'), ('Insurance', 'Insurance'), ('Utilities', 'Utilities'), ('Savings', 'Savings'), ('Maintenance & Repairs', 'Maintenance & Repairs'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
